"use client";

import { AdminApplicationsTable } from "../../AdminApplicationsTable";

export default function AdminApplicationsPage() {
  return (
    <div className="w-full py-10">
      <AdminApplicationsTable />
    </div>
  );
}
// Generated by Copilot
