"use client";

import { AdminCategoriesTable } from "../../AdminCategoriesTable";

export default function AdminCategoriesPage() {
  return (
    <div className="w-full py-10">
      <AdminCategoriesTable />
    </div>
  );
}
// Generated by Copilot
