"use client";

import { AdminCommentsTable } from "../../AdminCommentsTable";

export default function AdminCommentsPage() {
  return (
    <div className="w-full py-10">
      <AdminCommentsTable />
    </div>
  );
}
// Generated by Copilot
