"use client";

import { useQuery } from "@tanstack/react-query";
import { convexQuery } from "@convex-dev/react-query";
import { api } from "../../../convex/_generated/api";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";

export function AdminCommentsTable() {
  const { data, isPending, error } = useQuery(
    convexQuery(api.comments.getBestReviews, {})
  );

  if (isPending) {
    return (
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>User</TableHead>
            <TableHead>Job</TableHead>
            <TableHead>Text</TableHead>
            <TableHead>Updated At</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {[...Array(5)].map((_, i) => (
            <TableRow key={i}>
              {[...Array(4)].map((_, j) => (
                <TableCell key={j}>
                  <Skeleton className="h-4 w-20" />
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    );
  }

  if (error || !data) {
    return (
      <div className="text-red-500 text-center py-4">
        Error loading comments
      </div>
    );
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>User</TableHead>
          <TableHead>Job</TableHead>
          <TableHead>Text</TableHead>
          <TableHead>Updated At</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((c) => (
          <TableRow key={c.comment._id}>
            <TableCell>{c.user?.name ?? c.comment.userId}</TableCell>
            <TableCell>{c.comment.jobId}</TableCell>
            <TableCell>{c.comment.text}</TableCell>
            <TableCell>
              {c.comment.updatedAt
                ? new Date(c.comment.updatedAt).toLocaleString()
                : "-"}
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
// Generated by Copilot
