"use client";

import { useQuery } from "@tanstack/react-query";
import { convexQuery } from "@convex-dev/react-query";
import { api } from "../../../convex/_generated/api";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";

export function AdminApplicationsTable() {
  const { data, isPending, error } = useQuery(
    convexQuery(api.applications.getAllApplictions, {})
  );

  if (isPending) {
    return (
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Applicant</TableHead>
            <TableHead>Recruiter</TableHead>
            <TableHead>Job</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>SOP</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {[...Array(5)].map((_, i) => (
            <TableRow key={i}>
              {[...Array(5)].map((_, j) => (
                <TableCell key={j}>
                  <Skeleton className="h-4 w-20" />
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    );
  }

  if (error || !data) {
    return (
      <div className="text-red-500 text-center py-4">
        Error loading applications
      </div>
    );
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Applicant</TableHead>
          <TableHead>Recruiter</TableHead>
          <TableHead>Job</TableHead>
          <TableHead>Status</TableHead>
          <TableHead>SOP</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {data.map((app) => (
          <TableRow key={app._id}>
            <TableCell>{app.applicantId}</TableCell>
            <TableCell>{app.recruiterId}</TableCell>
            <TableCell>{app.jobId}</TableCell>
            <TableCell>{app.status}</TableCell>
            <TableCell>{app.sop}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
// Generated by Copilot
